spring:
   main:
      allow-circular-references: true

app:
  source:
    folder: "/home/azkaban/sftp-example/test"
  sftp:
    password: ''
    user: "azkaban"
    host: "localhost"
    port: 22
    timeout: 5000

